### ISSUE TITLE
remarkable fails on launch

### ISSUE THREAD

**Issue by yadayada** [remarkableapp/Remarkable-Linux#14] opened 2015-12-19 16:41 UTC
I'm using version 1.62 on Debian stretch.

Recently, I get the following error when I try to run remarkable

```
/usr/lib/python3/dist-packages/remarkable/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk # pylint: disable=E0611
/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 48, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3/dist-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 86, in add_from_file
    Gtk.Builder.add_from_file(self, filename)
GLib.Error: gtk-builder-error-quark: /usr/share/remarkable/ui/RemarkableWindow.ui:835:58 Object with ID  not found (13)
```

**Comment by FindHao** [comment] 2016-01-30 12:04
Got this problem too,after my upgrade from debian jessie to debian testing.

**Comment by mcbridet** [comment] 2016-02-08 05:49
+1

**Comment by gazrac** [comment] 2016-02-09 07:25
I have the same problem using Ubuntu Gnome 15.10

**Comment by ghost** [comment] 2016-02-09 18:10
I can confirm this issue.

On my Debian stretch I sloved this by editing /usr/share/remarkable/ui/RemarkableWindow.ui
I disabled all stuff from line 834 to 842 like this:

> ```
>            
> ```

This will disable the "About" menu entry in remarkables "Help" menu.  This will fix the start issue for me. Hope this will help you guys to fix your issues too

> $ remarkable --version
> remarkable 1.62

**Comment by mxmlnkn** [comment] 2016-02-09 21:13
I have the exact same problem with Debian sid. The only 3 hours old workaround by @sitzmoebelchronograph works, thank you. What a lucky coincidence :).
My configuration:

```
dpkg -l python3 python dconf-gsettings-backend gsettings-backend \
gir1.2-glib-2.0 gir1.2-gtk-3.0 python3-markdown python3-bs4 \
gir1.2-webkit-3.0 yelp wkhtmltopdf python3-gi remarkable

+++-========================-=================-=============
ii  dconf-gsettings-backend: 0.24.0-2          amd64        
ii  gir1.2-glib-2.0:amd64    1.46.0-3          amd64        
ii  gir1.2-gtk-3.0:amd64     3.18.7-1          amd64        
ii  gir1.2-webkit-3.0:amd64  2.4.9-3           amd64        
un  gsettings-backend        <none>            <none>       
ii  python                   2.7.11-1          amd64        
ii  python3                  3.4.3-7           amd64        
ii  python3-bs4              4.4.1-1           all          
ii  python3-gi               3.18.2-2          amd64        
ii  python3-markdown         2.6.5-2           all          
ii  remarkable               1.62              all          
ii  wkhtmltopdf              0.12.2.4-1        amd64        
ii  yelp                     3.16.1-1          amd64        
```

The packages above are copy pasted from the dependencies of 

```
apt-cache show -t sid remarkable
```

I installed this by using the debian package from here http://remarkableapp.github.io/linux/download.html and then

```
sudo dpkg -i remarkable_1.62_all.deb
sudo apt-get -f install -t sid
```

**Comment by ghost** [comment] 2016-02-09 21:33
@mxmlnkn U'r welcome. For me it looks like an issue in remarkable code (missing reference for mnu_about), because I can't run actually remarkable .deb Package on older Debian Systems as "stretch"

@remarkableapp Did you think you able to fix this issue in near future?

**Comment by docraddley** [comment] 2016-02-09 23:59
Fwiw, I only commented out line 835. This way you can still have "About" in "Help."

**Comment by KevinHu-1024** [comment] 2016-02-20 11:00
@sitzmoebelchronograph 

Thank you, that's pretty nice!

But when I start it from terminal, it still report a error.(Finally it works, remain the error in terminal).

Wait for next offical's update.

```
/usr/lib/python3/dist-packages/remarkable/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk # pylint: disable=E0611
/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
```

**Comment by excieve** [comment] 2016-03-05 18:06
Same issue on Fedora 23 with Gnome 3.18.2, also "fixed" with a workaround by @sitzmoebelchronograph.

**Comment by aaamourao** [comment] 2016-03-08 17:55
Same issue on Fedora 23 with Gnome 3! Thx,@sitzmoebelchronograph  !!

**Comment by yedamao** [comment] 2016-04-14 04:18
Same issue on ubuntu 16.04.
Thanks @sitzmoebelchronograph . It works

**Comment by anvius** [comment] 2016-04-20 16:16
Thanks @sitzmoebelchronograph . It works.
Thanks @Zaiyin too. At the end, I commented the line #835. It works too.

**Comment by TheInitializer** [comment] 2016-05-08 18:43
Having the same issue on Fedora 23 w/ Gnome

**Comment by TheInitializer** [comment] 2016-05-08 18:49
@Zaiyin it worked! Thanks so much

**Comment by iqbalhusen** [comment] 2016-05-09 06:54
+1 Thanks @sitzmoebelchronograph . It works.

**Comment by verbal007** [comment] 2016-06-14 19:03
Using Ubuntu GNOME 16.04 LTS and had same problem...  but it's now fixed!!
+1 Thanks @sitzmoebelchronograph

**Comment by wangarhat** [comment] 2016-06-16 02:58
@Zaiyin it works

**Comment by drvenom123** [comment] 2016-06-18 14:25
I'm having the same issue on Xubuntu 16.04. Unfortunately,   @sitzmoebelchronograph solution didn’t work for me. Any estimated time for a fix? Thanks.

**Comment by NathanJPlummer** [comment] 2016-06-23 02:04
Confirming:

Linux Mint 18 based on Ubuntu 16.04.  Only works with the workaround.

**Comment by remarkableapp** [comment] 2016-06-23 12:11
Updated DEB and RPM available in [this repository](https://github.com/remarkableapp/Remarkable-Linux) if you wish to test. Fixes #14 crash on launch.

Will be uploaded to site soon.

**Comment by gwillem** [comment] 2016-06-23 20:08
Thanks, the 1.72 deb works awesome on Ubuntu 16.04

**Closed as completed** 2016-06-24 04:12 UTC
Labels: priority

**Comment by baddwin** [comment] 2018-07-20 15:50
I've just installed this on Fedora 28 from COPR of _neteler/remarkable_ and still getting this issue and the workaround is not working any more

```
Traceback (most recent call last):
  File "/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3.6/site-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3.6/site-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

**Comment by NathanJPlummer** [comment] 2018-08-12 03:43
@baddwin 

Just a guess, but maybe something went wrong with that build in the repository?

Maybe try the RPM [direct from the Remarkable webpage](https://remarkableapp.github.io/linux/download.html)
