### ISSUE TITLE
startup error on Ubuntu 16.04

### ISSUE THREAD

**Issue by pyprism** [remarkableapp/Remarkable-Linux#27] opened 2016-04-23 19:05 UTC
`/usr/lib/python3/dist-packages/remarkable/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk # pylint: disable=E0611
/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit
*Spellchecking not enabled.
*To enable spellchecking install pygtkspellcheck
*https://pypi.python.org/pypi/pygtkspellcheck/
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 48, in main
    window = RemarkableWindow.RemarkableWindow()
  File "/usr/lib/python3/dist-packages/remarkable_lib/Window.py", line 52, in __new__
    builder = get_builder('RemarkableWindow')
  File "/usr/lib/python3/dist-packages/remarkable_lib/helpers.py", line 48, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 86, in add_from_file
    Gtk.Builder.add_from_file(self, filename)
GLib.Error: gtk-builder-error-quark: /usr/share/remarkable/ui/RemarkableWindow.ui:835:58 Object with ID  not found (13)
`

**Comment by mcampbell508** [comment] 2016-04-25 11:54
I can also confirm this, after upgrading to Ubuntu 16.04 - Remarkable does not start up and I receive the same errors above.

**Comment by TheInitializer** [comment] 2016-05-08 17:50
Having this same error in Fedora 23.

**Comment by yadayada** [comment] 2016-05-08 17:54
Please close this issue. It is a duplicate of #14.

**Comment by tuuna** [comment] 2016-05-26 07:35
the same,waiting for solutions

**Comment by Coeur-Noir** [comment] 2016-06-22 00:33
Same here https://forum.ubuntu-fr.org/viewtopic.php?id=1992200

**Comment by gwillem** [comment] 2016-06-24 08:14
Fixed by [1.75](https://github.com/remarkableapp/Remarkable-Linux)

**Closed as completed** 2016-06-25 21:13 UTC
Labels: bug, priority
